---
name: Continuous integration
on: push
jobs:
  lint:
    name: Lint source code
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@default
        with:
          version: 0.6.0
      - name: Check syntax
        run: find src -name '*.zig' | sort | xargs zig fmt --check
  test:
    name: Run unit tests
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@default
        with:
          version: 0.6.0
      - name: Run test suite
        run: zig test dogma.zig
